/**
 * CS DEPARTMENT MASTER DATABASE
 * Total Students: 374 | Total Classes: 9
 * Advisor names extracted from the last column of student list.
 */

const Database = {
  "I B.Sc CS with AI": {
    "advisor": "",
    "students": {}
  },
    
  "I B.Sc CS": {
  "advisor": "",
  "students": {}
  }, 
    
  "II B.Sc CS with AI": {
    "advisor": "Dr. S.P. SOUNDARIYA",
    "students": {
      "25BAR001": "MANIKANDAN A",
      "25BAR002": "ABHINANDHANA M",
      "25BAR003": "VISHNU KUMARAN R",
      "25BAR004": "KAVIYA R",
      "25BAR007": "MATHIVANAN A",
      "25BAR009": "SATHYA SEELAN M",
      "25BAR010": "SWATHI LAKSHMI S",
      "25BAR011": "PRAGADEESWARAN V",
      "25BAR012": "ANBUCHELVAN S A",
      "25BAR015": "KAVYA T",
      "25BAR016": "MOHAMMED AZARUDEEN G",
      "25BAR017": "NEHA R",
      "25BAR019": "ARAVINDHAN S",
      "25BAR020": "THARUN KUMAR M",
      "25BAR021": "DHARSHANA PRIYA D",
      "25BAR022": "DHARSHINI K",
      "25BAR023": "ABINAYA M",
      "25BAR024": "VIKRAMRAJ R",
      "25BAR025": "AJAY KUMAR M",
      "25BAR026": "KARTHI PRAKASH S",
      "25BAR027": "LEELAKRISHNAN M",
      "25BAR028": "REETHISRAJ S",
      "25BAR029": "MANIKANDARAJA M",
      "25BAR030": "GOKUL R",
      "25BAR031": "DELCY JANAT MARY V",
      "25BAR032": "SREE VISHNUVARTHAN J",
      "25BAR033": "KESAVARAJ K",
      "25BAR034": "KIRUTHICKRAJ S",
      "25BAR035": "MERLIN LISA E",
      "25BAR037": "THARAN KUMAR K V",
      "25BAR038": "MITHRAN J",
      "25BAR039": "SAJINA BEGUM M J",
      "25BAR040": "ARJUN S",
      "25BAR041": "DHARANITHARAN S",
      "25BAR042": "SRIHARSHAN U",
      "25BAR043": "ARUN KUMAR M",
      "25BAR044": "MRIDINI DEV M",
      "25BAR045": "MOHAMED IRFAN A",
      "25BAR046": "KABILAN R",
      "25BAR047": "NICKY MARSHAL S",
      "25BAR048": "MOHAMED SHEIK RASWAN V",
      "25BAR049": "GNANA PRAKASH C",
      "25BAR050": "KUNGUMA DHARSHINI S",
      "25BAR051": "ESTHER MARY D",
      "25BAR052": "VISHWA L",
      "25BAR053": "SAJWA FARHATH M.I",
      "25BAR054": "MAHASWETHA K S",
      "25BAR055": "GOKULRAM S"
    }
  },
  "III B.Sc. CS with AI": {
    "advisor": "Dr. P. Sukumar",
    "students": {
      "24BAR001": "SHAKRUDEEN M",
      "24BAR002": "NAVEEN S",
      "24BAR003": "NAVEEN J",
      "24BAR004": "KAVIYA S",
      "24BAR005": "DHARANIDHARAN K.C",
      "24BAR006": "ANANTHI U",
      "24BAR008": "MUTHU MARI K",
      "24BAR009": "GURUPRANAV P S",
      "24BAR011": "MADHU SHREE M",
      "24BAR012": "MUTHU GANESH G",
      "24BAR013": "SARATHI RAJ T",
      "24BAR014": "SHAFIQ AHAMED S",
      "24BAR015": "Niroshini B",
      "24BAR016": "SYED AFRIDI B S K",
      "24BAR017": "BHUBANA N",
      "24BAR018": "SHANMUGABOOPATHI M",
      "24BAR019": "PRANAV D S",
      "24BAR020": "MUGUNTHAN K",
      "24BAR021": "PRINCIYA V",
      "24BAR022": "HARINI K",
      "24BAR023": "YOGESHWARAN.V V",
      "24BAR024": "ARSH AHAMED A",
      "24BAR025": "DHARSHINI A",
      "24BAR026": "KABINATH S",
      "24BAR027": "ABDUL RAHMAN J",
      "24BAR031": "HARISH M",
      "24BAR032": "VISHVA RUBAN M",
      "24BAR033": "JOE TARCIOUS J",
      "24BAR034": "AKHIL S P R",
      "24BAR036": "OVIYA R H",
      "24BAR037": "NANDHA KISHORE M",
      "24BAR038": "AMRIN A",
      "24BAR039": "BARATH P",
      "24BAR040": "BALA VIGNESH S",
      "24BAR041": "SWETHA K"
    }
  },
  "II B.Sc. CS": {
    "advisor": "Dr. C. Vanitha",
    "students": {
      "25BCS004": "VISHNU M",
      "25BCS005": "HARI KOWSIK E",
      "25BCS006": "SETHUPATHI M",
      "25BCS007": "MOHAMMED ASHIK M",
      "25BCS008": "BRINDHA D",
      "25BCS009": "MOHAN PRASATH R.R",
      "25BCS011": "BARATH R",
      "25BCS012": "SOWMIYA M",
      "25BCS013": "RAGHUHARIHARAN A",
      "25BCS014": "VIGNESH K",
      "25BCS015": "VISHNU VARADHAN S",
      "25BCS016": "MOHEMED ELMUGTABA SULIMAN",
      "25BCS017": "DARSHAN S",
      "25BCS018": "SABARINATHAN B",
      "25BCS019": "KARTHIKEYAN K",
      "25BCS020": "VINO SREE N",
      "25BCS021": "DEEPAKALAIVANI G",
      "25BCS022": "NAVEENA S",
      "25BCS023": "GOWTHAM S",
      "25BCS024": "ADITHYA R",
      "25BCS025": "HASHVAN DEV S",
      "25BCS028": "SHIVANI R",
      "25BCS029": "TANZIL NIFAZ S",
      "25BCS030": "DINESH KUMAR S",
      "25BCS031": "MOHAMMED ARSHATH A",
      "25BCS032": "DARSHAN R",
      "25BCS033": "RAKSHIKA A",
      "25BCS035": "SATHISHWARAN K",
      "25BCS037": "SHINE RAJ J",
      "25BCS041": "DEEPESH M",
      "25BCS043": "NEELAKANDAN S",
      "25BCS044": "RIKSON A",
      "25BCS045": "SUBASH S",
      "25BCS046": "THIRISHA S",
      "25BCS047": "BEVINBRITHISHRAJA M",
      "25BCS048": "SIRANJEEVI T",
      "25BCS049": "THARUNIKA K",
      "25BCS050": "AJITHKUMAR K",
      "25BCS051": "SHESHAN RR",
      "25BCS052": "SUDESHNA A",
      "25BCS053": "ABINESH P",
      "25BCS054": "SAJID ABDULHALIM AMIN MOHAMED MOHAMED",
      "25BCS056": "ARIKARAN D",
      "25BCS057": "MADHIVASAN A",
      "25BCS058": "VIGNESH L",
      "25BCS059": "SASTIVELAN N",
      "25BCS060": "SAJEER S",
      "25BCS062": "ABDELRAHMAN MUSTAFA SIRELKHAFIM FARHAN",
      "25BCS063": "MOHANNED MOHAMED ELHASAN"
    }
  },
  "III B.Sc. CS": {
    "advisor": "Dr.R.Parameswari",
    "students": {
      "24BCS001": "AJITHKUMAR B",
      "24BCS005": "HARSHINI R",
      "24BCS006": "DEEPIKA K",
      "24BCS007": "KISHORE.M",
      "24BCS008": "ABISEIK J",
      "24BCS009": "MOHAMED YASAR H",
      "24BCS010": "BHUVANSHANKAR.B",
      "24BCS011": "RADHAKRISHNAN S",
      "24BCS012": "SAFWAN.A",
      "24BCS013": "JUMAIL AHAMED N",
      "24BCS014": "HARIPRIYA. R",
      "24BCS015": "MOHAMED NIYAZ",
      "24BCS016": "MOHAMMED ARSATH H",
      "24BCS017": "MOHAMED ASHIK",
      "24BCS018": "DINESH R",
      "24BCS019": "MURUGA SUTHAN U",
      "24BCS020": "AKILAN K",
      "24BCS022": "MANIKANDAN J",
      "24BCS023": "LOKESHWAR S",
      "24BCS024": "PRATHEEVRAJ",
      "24BCS025": "MUNISHWAR M",
      "24BCS027": "NAVEEN KUMAR",
      "24BCS028": "MANEESH .S",
      "24BCS029": "MADHAN.M",
      "24BCS030": "DEEPAK",
      "24BCS031": "NILA VS",
      "24BCS033": "P. RISHIKTHA",
      "24BCS034": "SUJITH V",
      "24BCS035": "FAATIH B",
      "24BCS036": "S.KAVIARASU",
      "24BCS037": "VINOTH KUMAR M",
      "24BCS038": "YUVA YOGESH.S",
      "24BCS039": "M SABARISH",
      "24BCS040": "D KEERTHIKA",
      "24BCS041": "RANJITHKUMAR M",
      "24BCS042": "SWADI R",
      "24BCS043": "MOHAMMEDIDREES. B",
      "24BCS044": "FATHIMA SHERIN.S",
      "24BCS045": "MATHIVANAN",
      "24BCS046": "MOHAMMED FAYYAS P M",
      "24BCS047": "ARUL KANNAN.S",
      "24BCS048": "G ROHAN RANGASWAMY",
      "24BCS049": "SACHIN SRI G",
      "24BCS050": "ABDHUL RAHAMAN.S",
      "24BCS051": "MUHAMMED AADHIL . N",
      "24BCS052": "M KAMESHWARAN",
      "24BCS053": "KAMALESH.M",
      "24BCS054": "R MOHAMED YAHYA",
      "24BCS055": "SUTHARSHAN.PG",
      "24BCS058": "MOHAMED OSMAN ALI ADAM",
      "24BCS059": "ARJUN P"
    }
  },
  "III B.Sc. CT": {
    "advisor": "Ms. N. Sukanya",
    "students": {
      "24BCT001": "CHIRANJEEVI M R",
      "24BCT003": "SARVESH KUMAR N",
      "24BCT004": "DEEPAK J",
      "24BCT005": "THIRUMALAI S",
      "24BCT006": "VINOTHAN C",
      "24BCT007": "PRAGADEESHWARAN P",
      "24BCT008": "ABHISHEK A",
      "24BCT009": "GURU BHARATHY S",
      "24BCT010": "SARAVANAN E",
      "24BCT011": "JASEMA ABBAS",
      "24BCT012": "KARTHIKEYAN R",
      "24BCT014": "YOGESH WARAN S",
      "24BCT015": "ATCHAYA R",
      "24BCT017": "MURALIDHARAN ANANDHAN",
      "24BCT018": "MOHAMMED AJMAL",
      "24BCT019": "SHAJIR A",
      "24BCT020": "VIVEKANATHAN P",
      "24BCT021": "ASHIK S",
      "24BCT023": "LIBI SANJAY K",
      "24BCT025": "SANJAI S",
      "24BCT026": "KAVIARASAN K",
      "24BCT101": "MAGESHWARAN R",
      "24BCT102": "MITHUN K",
      "24BCT103": "MANIKANDAN K",
      "24BCT105": "ELAKKIYA SELVAN E",
      "24BCT106": "PARASURAM R N",
      "24BCT107": "SATHEESH M",
      "24BCT108": "ISHWARIYA K",
      "24BCT109": "HARISH P",
      "24BCT110": "YOGESH A",
      "24BCT111": "VIGNESH E",
      "24BCT113": "MUTHURAJ S",
      "24BCT114": "DINESH KUMAR D",
      "24BCT115": "SUBHAHARINI S",
      "24BCT116": "SRIRAMAKRISHNAN G",
      "24BCT117": "KABILAN M",
      "24BCT118": "RAZAB NISHA Y",
      "24BCT119": "NANDHISH K",
      "24BCT120": "ADITHYAN K",
      "24BCT122": "HARISH ROHITH S",
      "24BCT123": "ELANGO A",
      "24BCT124": "RAGUPATHY M",
      "24BCT125": "PRITHIVIRAJ M",
      "24BCT126": "SAKTHI LAKSHMI A",
      "24BCT127": "SATHYA KEERTHANAN",
      "24BCT128": "ABINASH T",
      "24BCT129": "RITHISH KUMAR E",
      "24BCT130": "GANESH KUMAR K",
      "24BCT132": "KAVYA SRI T",
      "24BCT133": "SAI SAKTHI R K"
    }
  },
  "II M.Sc. CS": {
    "advisor": "Dr. R. Manimegalai",
    "students": {
      "25MCS001": "ANANDHAN K",
      "25MCS002": "KIFAYA K",
      "25MCS004": "SINENDIRA C",
      "25MCS006": "Divij C",
      "25MCS008": "GURUPRABHAKARAN M",
      "25MCS009": "RAHUL R",
      "25MCS010": "NAVEEN VISHNU G",
      "25MCS012": "YOGASRII D",
      "25MCS013": "AASHIKA K",
      "25MCS014": "PRITHIK R",
      "25MCS015": "SRIVATHSANGAN S",
      "25MCS017": "SAEED BAKHIT MOHAMED ABDELGADIR",
      "25MCS020": "LIYO ROSHAN A",
      "25MCS021": "AKSHAYA SREE S",
      "25MCS022": "ELNZER ALDAY MOHAMED ABDALGADIR",
      "25MCS023": "RAGHUL JOSEPHRAJ J",
      "25MCS024": "MENAKA N",
      "25MCS025": "AMIN ABDALATI ABDALKHAIR EID",
      "25MCS027": "MANJU M",
      "25MCS028": "CHINMAYAN V"
    }
    }
  };

const TamilNames = {
  "MANIKANDAN A": "மணிகண்டன் A",
  "ABHINANDHANA M": "அபிநந்தனா M",
  "VISHNU KUMARAN R": "விஷ்ணு குமரன் R",
  "KAVIYA R": "காவியா R",
  "MATHIVANAN A": "மதிவாணன் A",
  "SATHYA SEELAN M": "சத்ய சீலன் M",
  "SWATHI LAKSHMI S": "சுவாதி லக்ஷ்மி S",
  "PRAGADEESWARAN V": "பிரகதீஸ்வரன் V",
  "ANBUCHELVAN S A": "அன்புச்செல்வன் S A",
  "KAVYA T": "காவ்யா T",
  "MOHAMMED AZARUDEEN G": "முகமது அசாருதீன் G",
  "NEHA R": "நேஹா R",
  "ARAVINDHAN S": "அரவிந்தன் S",
  "THARUN KUMAR M": "தருண் குமார் M",
  "DHARSHANA PRIYA D": "தர்ஷனா பிரியா D",
  "DHARSHINI K": "தர்ஷினி K",
  "ABINAYA M": "அபினயா M",
  "VIKRAMRAJ R": "விக்ரம்ராஜ் R",
  "AJAY KUMAR M": "அஜய் குமார் M",
  "KARTHI PRAKASH S": "கார்த்தி பிரகாஷ் S",
  "LEELAKRISHNAN M": "லீலாகிருஷ்ணன் M",
  "REETHISRAJ S": "ரீதிஸ்ராஜ் S",
  "MANIKANDARAJA M": "மணிகண்டராஜா M",
  "GOKUL R": "கோகுல் R",
  "DELCY JANAT MARY V": "டெல்சி ஜானட் மேரி V",
  "SREE VISHNUVARTHAN J": "ஸ்ரீ விஷ்ணுவர்தன் J",
  "KESAVARAJ K": "கேசவராஜ் K",
  "KIRUTHICKRAJ S": "கிருத்திக்ராஜ் S",
  "MERLIN LISA E": "மெர்லின் லிசா E",
  "THARAN KUMAR K V": "தரண் குமார் K V",
  "MITHRAN J": "மித்ரன் J",
  "SAJINA BEGUM M J": "சஜினா பேகம் M J",
  "ARJUN S": "அர்ஜுன் S",
  "DHARANITHARAN S": "தரணிதரன் S",
  "SRIHARSHAN U": "ஸ்ரீஹர்ஷன் U",
  "ARUN KUMAR M": "அருண் குமார் M",
  "MRIDINI DEV M": "மிரிடினி தேவ் M",
  "MOHAMED IRFAN A": "முகமது இர்ஃபான் A",
  "KABILAN R": "கபிலன் R",
  "NICKY MARSHAL S": "நிக்கி மார்ஷல் S",
  "MOHAMED SHEIK RASWAN V": "முகமது ஷேக் ரஸ்வான் V",
  "GNANA PRAKASH C": "ஞான பிரகாஷ் C",
  "KUNGUMA DHARSHINI S": "குங்கும தர்ஷினி S",
  "ESTHER MARY D": "எஸ்தர் மேரி D",
  "VISHWA L": "விஷ்வா L",
  "SAJWA FARHATH M.I": "சஜ்வா ஃபர்ஹத் M.I",
  "MAHASWETHA K S": "மகாஸ்வேதா K S",
  "GOKULRAM S": "கோகுல்ராம் S",
  "SHAKRUDEEN M": "சக்ருதீன் M",
  "NAVEEN S": "நவீன் S",
  "NAVEEN J": "நவீன் J",
  "KAVIYA S": "காவியா S",
  "DHARANIDHARAN K.C": "தரணிதரன் K.C",
  "ANANTHI U": "ஆனந்தி U",
  "MUTHU MARI K": "முத்து மாரி K",
  "GURUPRANAV P S": "குருபிரணவ் P S",
  "MADHU SHREE M": "மது ஸ்ரீ M",
  "MUTHU GANESH G": "முத்து கணேஷ் G",
  "SARATHI RAJ T": "சாரதி ராஜ் T",
  "SHAFIQ AHAMED S": "ஷாஃபிக் அஹமத் S",
  "Niroshini B": "நிரோஷினி B",
  "SYED AFRIDI B S K": "சையத் அஃப்ரிடி B S K",
  "BHUBANA N": "புபனா N",
  "SHANMUGABOOPATHI M": "சண்முகப்பிரியா G K",
  "PRANAV D S": "பிரணவ் D S",
  "MUGUNTHAN K": "முகுந்தன் K",
  "PRINCIYA V": "பிரின்சியா V",
  "HARINI K": "ஹரிணி K",
  "YOGESHWARAN.V V": "யோகேஸ்வரன்.V V",
  "ARSH AHAMED A": "அர்ஷ் அஹமத் A",
  "DHARSHINI A": "தர்ஷினி A",
  "KABINATH S": "கபினாத் S",
  "ABDUL RAHMAN J": "அப்துல் ரஹ்மான் J",
  "HARISH M": "ஹரிஷ் M",
  "VISHVA RUBAN M": "விஷ்வா ரூபன் M",
  "JOE TARCIOUS J": "ஜோ டார்சியஸ் J",
  "AKHIL S P R": "அகில் S P R",
  "OVIYA R H": "ஓவியா R H",
  "NANDHA KISHORE M": "நந்தா கிஷோர் M",
  "AMRIN A": "அம்ரின் A",
  "BARATH P": "பரத் P",
  "BALA VIGNESH S": "பாலா விக்னேஷ் S",
  "SWETHA K": "ஸ்வேதா K",
  "VISHNU M": "விஷ்ணு M",
  "HARI KOWSIK E": "ஹரி கௌசிக் E",
  "SETHUPATHI M": "சேதுபதி M",
  "MOHAMMED ASHIK M": "முகமது ஆஷிக் M",
  "BRINDHA D": "பிருந்தா D",
  "MOHAN PRASATH R.R": "மோகன் பிரசாத் R.R",
  "BARATH R": "பரத் R",
  "SOWMIYA M": "சௌமியா M",
  "RAGHUHARIHARAN A": "ரகுஹரிஹரன் A",
  "VIGNESH K": "விக்னேஷ் K",
  "VISHNU VARADHAN S": "விஷ்ணு வரதன் S",
  "MOHEMED ELMUGTABA SULIMAN": "மோஹமெட் எல்முக்தபா சுலிமன்",
  "DARSHAN S": "தர்ஷன் S",
  "SABARINATHAN B": "சபரிநாதன் B",
  "KARTHIKEYAN K": "கார்த்திகேயன் K",
  "VINO SREE N": "வினோ ஸ்ரீ N",
  "DEEPAKALAIVANI G": "தீபகலைவாணி G",
  "NAVEENA S": "நவீனா S",
  "GOWTHAM S": "கௌதம் S",
  "ADITHYA R": "ஆதித்யா R",
  "HASHVAN DEV S": "ஹஷ்வன் தேவ் S",
  "SHIVANI R": "ஷிவானி R",
  "TANZIL NIFAZ S": "தன்ஸில் நிஃபாஸ் S",
  "DINESH KUMAR S": "தினேஷ் குமார் S",
  "MOHAMMED ARSHATH A": "முகமது அர்ஷத் A",
  "DARSHAN R": "தர்ஷன் R",
  "RAKSHIKA A": "ரக்ஷிகா A",
  "SATHISHWARAN K": "சதீஸ்வரன் K",
  "SHINE RAJ J": "ஷைன் ராஜ் J",
  "DEEPESH M": "தீபேஷ் M",
  "NEELAKANDAN S": "நீலகண்டன் S",
  "RIKSON A": "ரிக்சன் A",
  "SUBASH S": "சுபாஷ் S",
  "THIRISHA S": "திரிஷா S",
  "BEVINBRITHISHRAJA M": "பெவின்பிரித்திஷ்ராஜா M",
  "SIRANJEEVI T": "சிரஞ்சீவி T",
  "THARUNIKA K": "தருணிகா K",
  "AJITHKUMAR K": "அஜித்குமார் K",
  "SHESHAN RR": "ஷேஷன் RR",
  "SUDESHNA A": "சுதேஷ்ணா A",
  "ABINESH P": "அபினேஷ் P",
  "SAJID ABDULHALIM AMIN MOHAMED MOHAMED": "சாஜித் அப்துல்ஹாலிம் அமின் முகமது முகமது",
  "ARIKARAN D": "அரிகரன் D",
  "MADHIVASAN A": "மதிவாசன் A",
  "VIGNESH L": "விக்னேஷ் L",
  "SASTIVELAN N": "சஸ்திவேலன் N",
  "SAJEER S": "சஜீர் S",
  "ABDELRAHMAN MUSTAFA SIRELKHAFIM FARHAN": "அப்தெல்ரஹ்மான் முஸ்தபா சிராஎல்காபிம் ஃபர்ஹான்",
  "MOHANNED MOHAMED ELHASAN": "மோஹன்னெட் முகமது எல்ஹசன்",
  "AJITHKUMAR B": "அஜித்குமார் B",
  "HARSHINI R": "ஹர்ஷினி R",
  "DEEPIKA K": "தீபிகா K",
  "KISHORE.M": "கிஷோர்.M",
  "ABISEIK J": "அபிஷேக் J",
  "MOHAMED YASAR H": "முகமது யாசர் H",
  "BHUVANSHANKAR.B": "புவனசங்கர்.B",
  "RADHAKRISHNAN S": "ராதாகிருஷ்ணன் S",
  "SAFWAN.A": "சஃப்வான்.A",
  "JUMAIL AHAMED N": "ஜுமாயில் அஹமத் N",
  "HARIPRIYA. R": "ஹரிபிரியா. R",
  "MOHAMED NIYAZ": "முகமது நியாஸ்",
  "MOHAMMED ARSATH H": "முகமது அர்ஷத் H",
  "MOHAMED ASHIK": "முகமது ஆஷிக்",
  "DINESH R": "தினேஷ் R",
  "MURUGA SUTHAN U": "முருக சூதன் U",
  "AKILAN K": "அகிலன் K",
  "MANIKANDAN J": "மணிகண்டன் J",
  "LOKESHWAR S": "லோகேஷ்வர் S",
  "PRATHEEVRAJ": "பிரதீவ்ராஜ்",
  "MUNISHWAR M": "முனீஸ்வர் M",
  "NAVEEN KUMAR": "நவீன் குமார்",
  "MANEESH .S": "மனீஷ் .S",
  "MADHAN.M": "மதன்.M",
  "DEEPAK": "தீபக்",
  "NILA VS": "நிலா VS",
  "P. RISHIKTHA": "P. ரிஷிக்தா",
  "SUJITH V": "சுஜித் V",
  "FAATIH B": "ஃபாத்திஹ் B",
  "S.KAVIARASU": "S.கவியரசு",
  "VINOTH KUMAR M": "வினோத் குமார் M",
  "YUVA YOGESH.S": "யுவா யோகேஷ்.S",
  "M SABARISH": "M சபரிஷ்",
  "D KEERTHIKA": "D கீர்த்திகா",
  "RANJITHKUMAR M": "ரஞ்சித்குமார் M",
  "SWADI R": "ஸ்வாதி R",
  "MOHAMMEDIDREES. B": "முகமதுஇத்ரீஸ். B",
  "FATHIMA SHERIN.S": "பாத்திமா ஷெரின்.S",
  "MATHIVANAN": "மதிவாணன்",
  "MOHAMMED FAYYAS P M": "முகமது ஃபையாஸ் P M",
  "ARUL KANNAN.S": "அருள் கண்ணன்.S",
  "G ROHAN RANGASWAMY": "G ரோஹன் ரங்கசாமி",
  "SACHIN SRI G": "சச்சின் ஸ்ரீ G",
  "ABDHUL RAHAMAN.S": "அப்துல் ரஹ்மான்.S",
  "MUHAMMED AADHIL . N": "முஹம்மது ஆதில் . N",
  "M KAMESHWARAN": "M காமேஸ்வரன்",
  "KAMALESH.M": "கமலேஷ்.M",
  "R MOHAMED YAHYA": "R முகமது யாஹ்யா",
  "SUTHARSHAN.PG": "சுதர்ஷன்.PG",
  "MOHAMED OSMAN ALI ADAM": "முகமது உஸ்மான் அலி ஆதம்",
  "ARJUN P": "அர்ஜுன் P",
  "NAMITHRA SRI P": "நமித்ரா ஸ்ரீ P",
  "SARBESHWARAN A": "சர்பேஸ்வரன் A",
  "VINITH MATHEW R": "வினித் மேத்யூ R",
  "SHAFIQ AHAMED A": "ஷாஃபிக் அஹமத் A",
  "SUDHARSHAN M": "சுதர்ஷன் M",
  "RAHANISH": "ரஹனிஷ்",
  "UDHAYA VITHAL KADAM": "உதயா விதல் கடம்",
  "LOKITH P": "லோகித் P",
  "NITHYA SRI A S": "நித்யா ஸ்ரீ A S",
  "TAMILMANI K": "தமிழ்மணி K",
  "GOKUL D": "கோகுல் D",
  "PRATHAP R": "பிரதாப் R",
  "DINESH BABU K": "தினேஷ் பாபு K",
  "JERUSHA VERONICA": "ஜெருஷா வெரோனிகா",
  "VEERAKUMAR R": "வீரக்குமார் R",
  "SELVAMEENA": "செல்வமீனா",
  "SAKTHIVEL B": "சக்திவேல் B",
  "NAVEEN S A": "நவீன் S A",
  "BARATHRAJ M J": "பரத்ராஜ் M J",
  "PRASANTH": "பிரசாந்த்",
  "MANIKANDAN V": "மணிகண்டன் V",
  "DINESH": "தினேஷ்",
  "SRI HARINI R": "ஸ்ரீ ஹரிணி R",
  "VISHWANATH M": "விஸ்வநாத் M",
  "SARAN R": "சரண் R",
  "LENIN": "லெனின்",
  "PRIYADHARSHAN B": "பிரியதர்ஷன் B",
  "RAHUL U": "ராகுல் U",
  "GOWTHAM M": "கௌதம் M",
  "GOPIKA R": "கோபிகா R",
  "AQIL TAQQY A": "அகில் தாக்கி A",
  "AROKIASELVAN": "ஆரோக்கியசெல்வன்",
  "SHIVA GURU": "சிவா குரு",
  "GOWRISH": "கௌரிஷ்",
  "BOOPATHI A": "பூபதி A",
  "DHAKSHINA MOORTHY": "தக்ஷிணா மூர்த்தி",
  "THARANIYA LAKSHMI R": "தாரணியா லக்ஷ்மி R",
  "ARASU R": "அரசு R",
  "GURU G": "குரு G",
  "MOHAN": "மோகன்",
  "JAIDEV S": "ஜெய்தேவ் S",
  "ABHISHEK KRISHNAN A S": "அபிஷேக் கிருஷ்ணன் A S",
  "REVATHI S": "ரேவதி S",
  "SURESH R": "சுரேஷ் R",
  "SANJAY V": "சஞ்சய் V",
  "SAMRAJ S A": "சாம்ராஜ் S A",
  "MADESH": "மாதேஷ்",
  "BALA PRAVEEN B": "பாலா பிரவீன் B",
  "PANDI SELVAM R": "பாண்டி செல்வம் R",
  "MAYOORI B": "மயூரி B",
  "VIDHUN APOORVAN K": "விதுன் அபூர்வன் K",
  "SUJETH KUMAR K": "சுஜேத் குமார் K",
  "DEEPALIKA R": "தீபாலிகா R",
  "SAURAV V NAIR": "சௌரவ் V நாயர்",
  "ANBARASU S": "அன்பரசு S",
  "CHIRANJEEVI M R": "சிரஞ்சீவி M R",
  "SARVESH KUMAR N": "சர்வேஷ் குமார் N",
  "DEEPAK J": "தீபக் J",
  "THIRUMALAI S": "திருமலை S",
  "VINOTHAN C": "வினோதன் C",
  "PRAGADEESHWARAN P": "பிரகதீஸ்வரன் P",
  "ABHISHEK A": "அபிஷேக் A",
  "GURU BHARATHY S": "குரு பாரதி S",
  "SARAVANAN E": "சரவணன் E",
  "JASEMA ABBAS": "ஜாசெமா அப்பாஸ்",
  "KARTHIKEYAN R": "கார்த்திகேயன் R",
  "YOGESH WARAN S": "யோகேஷ் வரன் S",
  "ATCHAYA R": "அட்சயா R",
  "MURALIDHARAN ANANDHAN": "முரளிதரன் ஆனந்தன்",
  "MOHAMMED AJMAL": "முகமது அஜ்மல்",
  "SHAJIR A": "ஷாஜிர் A",
  "VIVEKANATHAN P": "விவேகநாதன் P",
  "ASHIK S": "ஆஷிக் S",
  "LIBI SANJAY K": "லிபி சஞ்சய் K",
  "SANJAI S": "சஞ்சை S",
  "KAVIARASAN K": "கவியரசன் K",
  "MAGESHWARAN R": "மகவேஸ்வரன் R",
  "MITHUN K": "மிதுன் K",
  "MANIKANDAN K": "மணிகண்டன் K",
  "ELAKKIYA SELVAN E": "இலக்கிய செல்வன் E",
  "PARASURAM R N": "பரசுராம் R N",
  "SATHEESH M": "சதீஷ் M",
  "ISHWARIYA K": "இஷ்வரியா K",
  "HARISH P": "ஹரிஷ் P",
  "YOGESH A": "யோகேஷ் A",
  "VIGNESH E": "விக்னேஷ் E",
  "MUTHURAJ S": "முத்துராஜ் S",
  "DINESH KUMAR D": "தினேஷ் குமார் D",
  "SUBHAHARINI S": "சுபஹாரிணி S",
  "SRIRAMAKRISHNAN G": "ஸ்ரீராமகிருஷ்ணன் G",
  "KABILAN M": "கபிலன் M",
  "RAZAB NISHA Y": "ரசப் நிஷா Y",
  "NANDHISH K": "நந்தீஷ் K",
  "ADITHYAN K": "ஆதித்யன் K",
  "HARISH ROHITH S": "ஹரிஷ் ரோஹித் S",
  "ELANGO A": "இளங்கோ A",
  "RAGUPATHY M": "ரகுபதி M",
  "PRITHIVIRAJ M": "பிரித்திவிராஜ் M",
  "SAKTHI LAKSHMI A": "சக்தி லக்ஷ்மி A",
  "SATHYA KEERTHANAN": "சத்ய கீர்த்தனன்",
  "ABINASH T": "அபினாஷ் T",
  "RITHISH KUMAR E": "ரித்திஷ் குமார் E",
  "GANESH KUMAR K": "கணேஷ் குமார் K",
  "KAVYA SRI T": "காவ்யா ஸ்ரீ T",
  "SAI SAKTHI R K": "சாய் சக்தி R K",
  "ANANDHAN K": "ஆனந்தன் K",
  "KIFAYA K": "கிஃபாயா K",
  "SINENDIRA C": "சினேந்திரா C",
  "Divij C": "திவிஜ் C",
  "GURUPRABHAKARAN M": "குருபிரபாகரன் M",
  "RAHUL R": "ராகுல் R",
  "NAVEEN VISHNU G": "நவீன் விஷ்ணு G",
  "YOGASRII D": "யோகாஸ்ரீ D",
  "AASHIKA K": "ஆஷிகா K",
  "PRITHIK R": "பிரித்திக் R",
  "SRIVATHSANGAN S": "ஸ்ரீவத்ஸங்கன் S",
  "SAEED BAKHIT MOHAMED ABDELGADIR": "சயீத் பக்கீத் முகமது அப்தெல்கதிர்",
  "LIYO ROSHAN A": "லியோ ரோஷன் A",
  "AKSHAYA SREE S": "அக்ஷயா ஸ்ரீ S",
  "ELNZER ALDAY MOHAMED ABDALGADIR": "எல்ன்ஸர் அல்தாய் முகமது அப்தால்கதிர்",
  "RAGHUL JOSEPHRAJ J": "ராகுல் ஜோசப்ராஜ் J",
  "MENAKA N": "மேனகா N",
  "AMIN ABDALATI ABDALKHAIR EID": "அமின் அப்தலதி அப்தால்கைர் ஈத்",
  "MANJU M": "மஞ்சு M",
  "CHINMAYAN V": "சின்மயன் V",
  "MADHAN M": "மதன் M",
  "GOMATHI S": "கோமதி S",
  "ANASWARA ANIL": "அனஸ்வரா அனில்",
  "ARIKARAN P": "அரிகரன் P",
  "MAZIN SHAMBATI": "மாசின் ஷம்பதி",
  "RITHISHA P": "ரித்திஷா P",
  "ISWARYA K": "ஐஸ்வர்யா K",
  "LYDIA MALARSINGH D": "லிடியா மலர்சிங் D",
  "THAMARAISELVAN. M": "தாமரைசெல்வன். M",
  "DHARANIDARAN S": "தரணிதரன் S",
  "ANISH KUMAR S": "அனிஷ் குமார் S",
  "ARUNAGIRI N": "அருணகிரி N",
  "VIGNESH KANNAN P": "விக்னேஷ் கண்ணன் P",
  "SAFIQ S": "ஷஃபிக் S",
  "ASWIN S": "அஸ்வின் S",
  "ELAKIYA N": "இலகியா N",
  "RAVISANKAR V": "ரவிசங்கர் V",
  "KEERTHANA S": "கீர்த்தனா S",
  "MADHUSHRI K A": "மதுஸ்ரீ K A",
  "MANUSH G": "மனுஷ் G",
  "DINESH KUMAR M": "தினேஷ் குமார் M",
  "PREM KUMAR A": "பிரேம் குமார் A",
  "DHEERAJ K P": "தீரஜ் K P",
  "ASWIHA K M": "அஸ்விஹா K M",
  "SUVETHA SRI V": "சுவேதா ஸ்ரீ V",
  "ABDUL THOWFIK A": "அப்துல் தௌஃபிக் A",
  "PRINEETH M": "பிரினித் M",
  "SHANMUGAPRIYA G K": "சண்முகப்பிரியா G K",
  "HARINI SRIE S S": "ஹரிணி ஸ்ரீ S S",
  "AMZATH A": "அம்ஸத் A",
  "SIVAGANESH G": "சிவ கணேஷ் G",
  "R MYVIKRAM": "R மைவிக்ரம்",
  "DHARANISHKUMAR M J": "தரணிஷ்குமார் M J",
  "BHUVANESHWARI S": "புவனேஸ்வரி S",
  "UBAIS F": "உபாய்ஸ் F",
  "HARIVARTTHAN K": "ஹரிவர்த்தன் K",
  "PRASANNA V": "பிரசன்னா V",
  "DHARSHINI N": "தர்ஷினி N",
  "VISHNU A": "விஷ்ணு A",
  "BHARATHRAJ A": "பரத்ராஜ் A",
  "THARUN M J": "தருண் M J",
  "JISHORE M": "ஜிஷோர் M",
  "MAYUR P": "மயூர் P",
  "NISHA K": "நிஷா K",
  "PRABAKARAN S": "பிரபாகரன் S",
  "MOHAMMED IRFAN S": "முகமது இர்ஃபான் S",
  "KARTHICK D": "கார்த்திக் D",
  "MADHUMITHA S": "மதுமிதா S",
  "KONDEPUDI MEENAKSHI": "கொண்டெபுடி மீனாட்சி",
  "PRAVEEN S": "பிரவீன் S",
  "SIVARANJANI M": "சிவராஞ்சனி M",
  "ABHINAYESWARI C": "அபினயேஸ்வரி C",
  "RUTHRAMOORTHI K J": "ருத்ரமூர்த்தி K J",
  "LINGA DURAI B": "லிங்கா துரை B",
  "LIEJO S": "லீஜோ S",
  "SUBASRI M": "சுபாஸ்ரீ M",
  "SABARI VARUN R": "சபரி வருண் R",
  "MOHAMMED SHAMIL A": "முகமது ஷாமில் A",
  "PRAVEEN R": "பிரவீன் R",
  "GOWTHAMAN S": "கௌதமன் S",
  "AKASH R": "ஆகர்ஷ் R",
  "SIVA PANDIAN M": "சிவ பாண்டியன் M",
  "SIVASRITHAR K": "சிவஸ்ரீதர் K",
  "MOHAMMED YUSUF M": "முகமது யூசுப் M",
  "HARISHANKAR A": "ஹரிசங்கர் A"
};
